FROM node:22-alpine AS dependencies

WORKDIR /app

COPY package.json yarn.lock ./
COPY tsconfig.base.json nx.json ./

RUN yarn config set network-timeout 600000 -g
RUN yarn cache clean
RUN yarn install --frozen-lockfile

COPY libs/ ./libs/