networks:
  app-network:
    external: true
    name: demo-t3-network

x-logging: &default-logging
  driver: json-file
  options:
    max-size: '10m'
    max-file: '72'

services:
  # Frontend (React + NGINX) - Only service with external access
  client-mx:
    build:
      context: .
      dockerfile: apps/client-mx/Dockerfile
    depends_on:
      - server-nest
    ports:
      - '80:80' # Standard HTTP port
      - '443:443' # Standard HTTPS port
    volumes:
      - /opt/demo-t3-shared/letsencrypt:/etc/letsencrypt:ro
      - /opt/demo-t3-shared/www-certbot:/var/www/certbot:ro
    env_file:
      - .env.production
    networks:
      - app-network
    restart: unless-stopped
    logging: *default-logging
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost/']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # API Service (NestJS) - Internal only, no external ports
  server-nest:
    build:
      context: .
      dockerfile: apps/server-nest/Dockerfile
    # No external ports - only accessible via nginx proxy
    depends_on:
      - auth-service
    env_file:
      - .env.production
    environment:
      SERVICE_NAME: server-nest
    networks:
      - app-network
    restart: unless-stopped
    logging: *default-logging
    healthcheck:
      test:
        [
          'CMD',
          'curl',
          '-f',
          'http://localhost:${NX_PUBLIC_SERVER_NEST_PORT:-8083}/api/health-check',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Auth Service (NestJS + Prisma) - Internal only, no external ports
  auth-service:
    build:
      context: .
      dockerfile: apps/auth-service/Dockerfile
      args:
        NX_PUBLIC_AUTH_SERVICE_PORT: ${NX_PUBLIC_AUTH_SERVICE_PORT:-8084}
    # No external ports - internal service only
    env_file:
      - .env.production
    environment:
      SERVICE_NAME: auth-service
    networks:
      - app-network
    restart: unless-stopped
    logging: *default-logging
    healthcheck:
      test:
        [
          'CMD',
          'curl',
          '-f',
          'http://localhost:${NX_PUBLIC_AUTH_SERVICE_PORT:-8084}/api/health-check',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # # AlertManager - Alert notifications
  # alertmanager:
  #   image: prom/alertmanager:latest
  #   ports:
  #     - '127.0.0.1:${NX_PUBLIC_ALERTMANAGER_PORT:-9093}:9093'
  #   volumes:
  #     - ./monitoring/alertmanager:/etc/alertmanager
  #   command:
  #     - '--config.file=/etc/alertmanager/alertmanager.yml'
  #     - '--storage.path=/alertmanager'
  #     - '--web.external-url=http://localhost:${NX_PUBLIC_ALERTMANAGER_PORT:-9093}'
  #   networks:
  #     - app-network
  #   restart: unless-stopped

  # # Node Exporter - System metrics
  # node-exporter:
  #   image: prom/node-exporter:latest
  #   ports:
  #     - "9100:9100"
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /:/rootfs:ro
  #   command:
  #     - '--path.procfs=/host/proc'
  #     - '--path.rootfs=/rootfs'
  #     - '--path.sysfs=/host/sys'
  #     - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
  #   networks:
  #     - app-network
  #   restart: unless-stopped

  # # cAdvisor - Container metrics
  # cadvisor:
  #   image: gcr.io/cadvisor/cadvisor:latest
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:rw
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #     - /dev/disk/:/dev/disk:ro
  #   privileged: true
  #   devices:
  #     - /dev/kmsg:/dev/kmsg
  #   networks:
  #     - app-network
  #   restart: unless-stopped

  # # PostgreSQL Exporter - Database metrics
  # postgres-exporter:
  #   image: prometheuscommunity/postgres-exporter:latest
  #   environment:
  #     DATA_SOURCE_NAME: "postgresql://${NX_PUBLIC_AUTH_DB_POSTGRES_USER}:${NX_PUBLIC_AUTH_DB_POSTGRES_PASSWORD}@postgres:5432/${NX_PUBLIC_AUTH_DB_POSTGRES_DB}?sslmode=disable"
  #   ports:
  #     - "9187:9187"
  #   networks:
  #     - app-network
  #   restart: unless-stopped
  #   depends_on:
  #     - postgres

  # # Redis Exporter - Redis metrics
  # redis-exporter:
  #   image: oliver006/redis_exporter:latest
  #   environment:
  #     REDIS_ADDR: "redis://redis:6379"
  #   ports:
  #     - "9121:9121"
  #   networks:
  #     - app-network
  #   restart: unless-stopped
  #   depends_on:
  #     - redis

  # # NGINX Exporter - NGINX metrics
  # nginx-exporter:
  #   image: nginx/nginx-prometheus-exporter:latest
  #   command:
  #     - '-nginx.scrape-uri=http://client-mx:80/nginx_status'
  #   ports:
  #     - "9113:9113"
  #   networks:
  #     - app-network
  #   restart: unless-stopped
  #   depends_on:
  #     - client-mx
