server:
  disable: false
  http_listen_port: 9080

clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /data/positions.yaml

scrape_configs:
  - job_name: docker-logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    pipeline_stages:
      - docker: {}
      # Parse structured JSON logs emitted by Nest services
      - match:
          selector: '{service=~"(server-nest|auth-service)"}'
          stages:
            - json:
                expressions:
                  timestamp: timestamp
                  level: level
                  message: message
                  context: context
                  service: service
                  method: method
                  url: url
                  statusCode: statusCode
                  responseTime: responseTime
                  userId: userId
                  userAgent: userAgent
                  ip: ip
            - timestamp:
                source: timestamp
                format: '2006-01-02 15:04:05.000'
            - labels:
                level:
                context:
                service:
                method:
                url:
                statusCode:
      - match:
          selector: '{container=~".+"}'
          stages:
            - drop:
                # Drop only lines that include sensitive headers explicitly
                expression: '(?i)(authorization:|set-cookie:|x-api-key:|api-key:|x-auth-token:|password=)'
                drop_counter_reason: 'sensitive_data_filtered'
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container'
        regex: '/(.*)'
      - source_labels:
          ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'
      - source_labels:
          ['__meta_docker_container_label_com_docker_compose_project']
        target_label: 'project'
      - source_labels:
          ['__meta_docker_container_label_com_docker_compose_container_number']
        target_label: 'container_number'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'
      - source_labels: ['__meta_docker_network_name']
        target_label: 'network'
      - source_labels:
          ['__meta_docker_container_label_org_opencontainers_image_title']
        target_label: 'image_title'
      - source_labels:
          ['__meta_docker_container_label_org_opencontainers_image_version']
        target_label: 'image_version'
