server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  - job_name: docker-logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    pipeline_stages:
      - docker: {}
      - match:
          selector: '{container_name=~".+"}'
          stages:
            - regex:
                expression: '(?i)(authorization|password|token|set-cookie)'
                source: log
            - labeldrop:
                - __match_group_1
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container'
        regex: '/(.*)'
      - source_labels:
          ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'
      - source_labels:
          ['__meta_docker_container_label_com_docker_compose_project']
        target_label: 'project'
      - source_labels:
          ['__meta_docker_container_label_com_docker_compose_container_number']
        target_label: 'container_number'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'
      - source_labels: ['__meta_docker_network_name']
        target_label: 'network'
      - source_labels:
          ['__meta_docker_container_label_org_opencontainers_image_title']
        target_label: 'image_title'
      - source_labels:
          ['__meta_docker_container_label_org_opencontainers_image_version']
        target_label: 'image_version'
