server:
  http_listen_port: 3100

auth_enabled: false

common:
  path: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  compactor:
    working_directory: /loki/compactor
    shared_store: filesystem
    compaction_interval: 5m
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules
  ring:
    kvstore:
      store: inmemory
  # alertmanager_url: http://alertmanager:9093

limits_config:
  retention_period: 7d
  ingestion_rate_mb: 4
  ingestion_burst_size_mb: 16
  reject_old_samples: true
  reject_old_samples_max_age: 168h
